### PR TITLE
DRUID-42-Work-on-about-us-Sulaimon

### PR DESCRIPTION
**Pull request by ekundayoSO**
Checking if the changes will be approved and I can continue the rest.

### CODE REVIEW

**Comment by adelansari** [comment]
Can you add more context related to what you did as in are there changes on the content side in drupal too?
Please put a screenshot of how the website looks after your changes so we can review and compare.

**Review by hetti-r — APPROVED** [review]
The about us page works for me

**Review by naveedshahid08 — APPROVED** [review]
Not working for me. I see it is working on Toni's computer but I can't see any style as Toni's does.

**Comment by hetti-r** [comment]
> The about us page works for me

actually I didn't see the changes sorry, I didn't see the picture here so I assumed I saw the changes.

**Review by adelansari — APPROVED** [review]
- Added a new co-author
- Move page styling to "styles" directory and removed redundant css file in src/css
- Simplify AboutUs component and remove DOMPurify sanitization. Page loads way faster now

Checked the website and it looks as expected:
image

**Comment by naveedshahid08** [comment]
Not working for me. I see it is working on Toni's computer but I can't see any style as Toni's does.

**Comment by naveedshahid08** [comment]
Not working for me. I see it is working on Toni's computer but I can't see any style as Toni's does.

**Review by ToniAndstrom — COMMENTED** [review]
I can see the css changes on the page.

**Comment by adelansari** [comment]
> Not working for me. I see it is working on Toni's computer but I can't see any style as Toni's does.

@naveedshahid08 , Please make sure to login to http://druid-final-project-team1.lndo.site/

**Pull request closed without merging**
