### PR TITLE
Update to AboutUs css

### PR DESCRIPTION
**Pull request by ekundayoSO**
Changes done by Sulaimon to be reviewed
image

### CODE REVIEW

**Comment by adelansari** [comment]
Missing the db so I cannot view the last changes :(

**Comment by adelansari** [comment]
- Added changes in both DB and css. 
- Fixed styling to make it adaptive for light and dark mode. 
- Added responsiveness for different screen sizes using tailwind properties
- Refactored the code

In Desktop:
image
image


In medium screen:
image


In small screen:
image

**Comment by ekundayoSO** [comment]
It's working in my machine. It looks very good also.

**Review by ToniAndstrom — APPROVED** [review]
Tested. Looks good to me

**Pull request merged**
